export default {
    en: {
        PLAY_GAME: "Play Game",
        SETTINGS: "Settings",
        EXIT_GAME: "Exit Game",
        CHOOSE_LANGUAGE: "Choose a language: ",
        INVALID_CHOICE: "Invalid choice, please try again.",
        SETTINGS_MENU: "Settings",
        PLACE_MARK: "Place your mark (e.g., A 1 or 1 A):",
        PLAYER_1: "Player 1",
        PLAYER_2: "Player 2",
        TURN: "it's your turn",
        DRAW: "Draw!",
        WINNER: "Winner is",
        COMPUTER_WIN: "The computer has won the game!",
        GAME_OVER: "Game Over",
        PLAY_AGAIN_QUESTION: "Do you want to play again? (yes/no)",
        CONFIRM: ["y", "yes"],
        DENY: ["n", "no"],
    },
    no: {
        PLAY_GAME: "Start spill",
        SETTINGS: "Innstillinger",
        EXIT_GAME: "Avslutt Spill",
        CHOOSE_LANGUAGE: "Velg et språk: ",
        INVALID_CHOICE: "Ugyldig valg, prøv igjen.",
        SETTINGS_MENU: "Innstillinger",
        PLACE_MARK: "Plasser markeringen din (f.eks. A 1 eller 1 A):",
        PLAYER_1: "Spiller 1",
        PLAYER_2: "Spiller 2",
        TURN: "det er din tur",
        DRAW: "Uavgjort!",
        WINNER: "Vinneren er",
        COMPUTER_WIN: "Datamaskinen har vunnet spillet!",
        GAME_OVER: "Spillet er over",
        PLAY_AGAIN_QUESTION: "Vil du spille igjen? (ja/nei)",
        CONFIRM: ["j", "ja"],
        DENY: ["n", "nei"],
    },
    de: {
        PLAY_GAME: "Spiel spielen",
        SETTINGS: "Einstellungen",
        EXIT_GAME: "Spiel verlassen",
        CHOOSE_LANGUAGE: "Wählen Sie eine Sprache: ",
        INVALID_CHOICE: "Ungültige Wahl, bitte versuchen Sie es erneut.",
        SETTINGS_MENU: "Einstellungen",
        PLACE_MARK: "Platzieren Sie Ihre Markierung (z.B. A 1 oder 1 A):",
        PLAYER_1: "Spieler 1",
        PLAYER_2: "Spieler 2",
        TURN: "du bist dran",
        DRAW: "Unentschieden!",
        WINNER: "Der Gewinner ist",
        COMPUTER_WIN: "Der Computer hat das Spiel gewonnen!",
        GAME_OVER: "Spiel beendet",
        PLAY_AGAIN_QUESTION: "Möchten Sie noch einmal spielen? (ja/nein)",
        CONFIRM: ["j", "ja"],
        DENY: ["n", "nein"],
    },
    es: {
        PLAY_GAME: "Jugar",
        SETTINGS: "Configuración",
        EXIT_GAME: "Salir del Juego",
        CHOOSE_LANGUAGE: "Elige un idioma: ",
        INVALID_CHOICE: "Elección inválida, intenta de nuevo.",
        SETTINGS_MENU: "Configuración",
        PLACE_MARK: "Coloca tu marca (por ejemplo, A 1 o 1 A):",
        PLAYER_1: "Jugador 1",
        PLAYER_2: "Jugador 2",
        TURN: "es tu turno",
        DRAW: "¡Empate!",
        WINNER: "El ganador es",
        COMPUTER_WIN: "¡La computadora ha ganado el juego!",
        GAME_OVER: "Juego terminado",
        PLAY_AGAIN_QUESTION: "¿Quieres jugar otra vez? (sí/no)",
        CONFIRM: ["s", "sí"],
        DENY: ["n", "no"],
    },
    fr: {
        PLAY_GAME: "Jouer",
        SETTINGS: "Paramètres",
        EXIT_GAME: "Quitter le Jeu",
        CHOOSE_LANGUAGE: "Choisissez une langue: ",
        INVALID_CHOICE: "Choix invalide, veuillez réessayer.",
        SETTINGS_MENU: "Paramètres",
        PLACE_MARK: "Placez votre marque (ex: A 1 ou 1 A):",
        PLAYER_1: "Joueur 1",
        PLAYER_2: "Joueur 2",
        TURN: "c'est ton tour",
        DRAW: "Match nul!",
        WINNER: "Le gagnant est",
        COMPUTER_WIN: "L'ordinateur a gagné le jeu!",
        GAME_OVER: "Jeu terminé",
        PLAY_AGAIN_QUESTION: "Voulez-vous rejouer? (oui/non)",
        CONFIRM: ["o", "oui"],
        DENY: ["n", "non"],
    },
    ko: {
        PLAY_GAME: "게임 시작",
        SETTINGS: "설정",
        EXIT_GAME: "게임 종료",
        CHOOSE_LANGUAGE: "언어를 선택하세요: ",
        INVALID_CHOICE: "잘못된 선택입니다. 다시 시도해주세요.",
        SETTINGS_MENU: "설정",
        PLACE_MARK: "표시를 놓으세요 (예: A 1 또는 1 A):",
        PLAYER_1: "플레이어 1",
        PLAYER_2: "플레이어 2",
        TURN: "당신 차례입니다",
        DRAW: "비겼습니다!",
        WINNER: "우승자는",
        COMPUTER_WIN: "컴퓨터가 게임에서 이겼습니다!",
        GAME_OVER: "게임 종료",
        PLAY_AGAIN_QUESTION: "다시 플레이 하시겠습니까? (예/아니요)",
        CONFIRM: ["y", "예"],
        DENY: ["n", "아니오"],
    },
    jp: {
        PLAY_GAME: "ゲームをする",
        SETTINGS: "設定",
        EXIT_GAME: "ゲームを終了する",
        CHOOSE_LANGUAGE: "言語を選んでください：",
        PLACE_MARK: "マークを置いてください（例：A 1 または 1 A）：",
        PLAYER_1: "プレイヤー 1 (X)",
        PLAYER_2: "プレイヤー 2 (O)",
        TURN: "あなたの番です",
        DRAW: "引き分けです！",
        WINNER: "勝者は",
        COMPUTER_WIN: "コンピュータがゲームに勝ちました！",
        GAME_OVER: "ゲームオーバー",
        PLAY_AGAIN_QUESTION: "もう一度プレイしますか？ (はい/いいえ)",
        CONFIRM: ["はい", "ハイ"],
        DENY: ["いいえ", "いいえ"],
    },
};
